language: node_js
sudo: false
node_js: stable
install:
    - npm install -g bower
    - npm install
script:
    - bower install --production
    - npm run build
    - bower install
    - npm run test
